import React, { useEffect } from "react";
import Head from "next/head";
import MainHeader from "@/components/main-header";
import { useRouter } from "next/router";
import { useGetTodoByIdMutation } from "@/services/todo";

function Details() {
  const router = useRouter();
  const [todo, result] = useGetTodoByIdMutation();

  const { id } = router.query;

  const todoId = parseInt(id);
  useEffect(() => {
    todo({
      id: parseInt(todoId),
    });
  }, []);

  console.log(result);

  return (
    <>
      <Head>
        <title>Todo Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen overflow-hidden">
        <MainHeader />
        <div className="max-w-xl shadow p-4 mx-auto min-h-[400px]">
          <h3 className="text-xl font-medium text-center">
            {result.data?.result.title}
          </h3>

          <h6 className="font-medium">Description</h6>
          <p className="text-sm text-gray-500">
            {result.data?.result.description}
          </p>
        </div>
      </div>
    </>
  );
}

export default Details;
